[tool.poetry]
name = "ml"
version = "0.1.0"
description = ""
authors = ["NicolasNewman <nnewman316@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
wordcloud = "^1.9.1.1"
nlpretext = "^1.2.1"
scikit-learn = "^1.2.2"
pandas = "^2.0.1"
nltk = "^3.8.1"


[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
